package org.viators.personalfinanceapp.exceptions;

public enum ErrorCodeEnum {
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    BUSINESS_VALIDATION_FAILED,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    INVALID_STATE,
    VALIDATION_FAILED,
    DATA_INTEGRITY_VIOLATION,
    MALFORMED_REQUEST,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    MISSING_REQUIRED_QUERY_PARAMETER,
    TYPE_MISMATCH,
    ENDPOINT_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
